#!/bin/sh

if [ "${DOCKER_SETENV:-UNDEF}" = "DEF" ]; then
    return 0
fi
DOCKER_SETENV="DEF"

DOCKERFILE_PATH_NGINX="nginx/Dockerfile"
IMAGE_BUILD_DIRECTRY_NGINX="nginx"
IMAGE_REPO_NGINX=""

DOCKERFILE_PATH_NODE="node/Dockerfile"
IMAGE_BUILD_DIRECTRY_NODE="node"
IMAGE_REPO_NODE=""

DOCKERFILE_PATH_ADMIN="admin/Dockerfile"
IMAGE_BUILD_DIRECTRY_ADMIN="admin"
IMAGE_REPO_ADMIN=""

